### ISSUE TITLE
module name should be noun_adjective, not adjective_noun

### ISSUE THREAD

**Issue by taylor-bsg** [bespoke-silicon-group/basejump_stl#200] opened 2019-12-03 20:02 UTC
https://github.com/bespoke-silicon-group/basejump_stl/blob/6dd02f7bf07da306620c90774b4a02825a054d87/bsg_dataflow/bsg_stable_sort.v#L15

Hi Ling can you rename this module (and its users) to be bsg_sort_stable? We put the adjective after the noun (or adverb after the verb) so that related modules will appear together in an alphabetical list.

**Comment by taylor-bsg** [comment] 2019-12-03 20:06
@tanglingshu

**Comment by tanglingshu** [comment] 2019-12-14 07:27
Issue fix is under pull request #208 

However, I suggest other changes such as:

1) remove bsg_sbox_ctrl.v (it is a duplicate of bsg_sbox_ctrl_concentrate.v)
2) remove bsg_sort_4.v (it specifies items_p=4, but can be generalized by using bsg_sort_stable.v)
3) remove bsg_stable_sort.v since it will now be replaced by bsg_sort_stable.v

**Comment by taylor-bsg** [comment] 2019-12-15 15:04
Thanks! Maybe do another pull request with these changes?

**Comment by taylor-bsg** [comment] 2020-01-10 01:16
@tanglingshu

**Comment by dpetrisko** [comment] 2020-06-15 15:28
Closed with #208

**Closed by dpetrisko** 2020-06-15 15:28 UTC
